# Generated by Django 5.0.1 on 2025-01-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelinherit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('teacher_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
