# Generated by Django 5.0.1 on 2025-01-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuform', '0002_modelinherit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelinherit',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
