# Generated by Django 5.0.1 on 2025-01-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuform', '0003_alter_modelinherit_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
