# Generated by Django 5.0.1 on 2025-01-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuform', '0004_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Lame',
        ),
    ]
